### ISSUE TITLE
enforceInterface() expected 'com.google.android.gms.ads.clearcut.IClearcut' but read 'com.google.android.gms.gass.internal.clearcut.IClearcut'

### ISSUE THREAD

**Issue by zenkog** [bdlukaa/native_admob_flutter#57]
All was good until suddenly this happens.
This is on Android.

I'm using version 1.3.0

My code:

```
// Initialize in main.dart

 await MobileAds.initialize(rewardedAdUnitId: AdManager.rewardedAdUnitId);
 await MobileAds.setTestDeviceIds(AdManager.adDevices);


// Then in the page to show ads:

void _onRewardAdEvent(Map<RewardedAdEvent, dynamic> adEvents) {
    try {
      final event = adEvents.keys.first;

      switch (event) {
        case RewardedAdEvent.loading:
          break;
        case RewardedAdEvent.loaded:
          print('*** Ad Loaded!');
          setState(() {
            isAdsLoading = false;
          });
          break;
        case RewardedAdEvent.loadFailed:
          final error = adEvents.values.first;
          print('Error Rewarded Video Ad failed to load: $error');
          break;
        case RewardedAdEvent.showed:
          print('*** Ad showed');

          break;
        case RewardedAdEvent.showFailed:
          final error = adEvents.values.first;
          print('show failed $error');
          break;
        case RewardedAdEvent.closed:
          print('*** Ad closed');
          if (!isRewardGiven) {
            setState(() {
              isAdsLoading = true;
            });
            if (_rewardedAd != null && !_rewardedAd.isAvailable) _rewardedAd.load();
          }
          break;
        case RewardedAdEvent.earnedReward:
          print('*** Rewarded Ad successful.');

          isRewardGiven = true;
          
          // Give reward here

          break;
        default:
          break;
      }
    } catch (error) {
      print('Error in _onRewardedAdEvent: $error');
      BlocProvider.of<IapCubit>(context).onErrorCaught(error);
    }
  }
```

I got this error message immediately once loading:

```
W/Parcel  (24079): **** enforceInterface() expected 'com.google.android.gms.ads.clearcut.IClearcut' but read 'com.google.android.gms.gass.internal.clearcut.IClearcut'
I/DynamiteModule(24079): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210890500
I/DynamiteModule(24079): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210890500
E/Ads     (24079): Couldn't create RTB adapter : 
E/Ads     (24079): android.os.RemoteException
E/Ads     (24079): 	at com.google.android.gms.internal.ads.zzapt.zzf(com.google.android.gms:play-services-ads-lite@@20.0.0:4)
E/Ads     (24079): 	at com.google.android.gms.internal.ads.zzapv.zzbz(com.google.android.gms:play-services-ads-lite@@20.0.0:6)
E/Ads     (24079): 	at com.google.android.gms.internal.ads.zzhw.onTransact(com.google.android.gms:play-services-ads-base@@20.0.0:3)
E/Ads     (24079): 	at android.os.Binder.transact(Binder.java:949)
E/Ads     (24079): 	at gc.ba(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:2)
E/Ads     (24079): 	at com.google.android.gms.ads.internal.mediation.client.b.e(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:1)
E/Ads     (24079): 	at com.google.android.gms.ads.nonagon.signals.dd.a(Unknown Source:4)
E/Ads     (24079): 	at aaa.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:2)
E/Ads     (24079): 	at zn.run(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:3)
E/Ads     (24079): 	at aac.run(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
E/Ads     (24079): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Ads     (24079): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Ads     (24079): 	at java.lang.Thread.run(Thread.java:919)
E/Ads     (24079): Error calling adapter: com.google.ads.mediation.applovin.AppLovinMediationAdapter
E/Ads     (24079): Couldn't create RTB adapter : 
E/Ads     (24079): android.os.RemoteException
E/Ads     (24079): 	at com.google.android.gms.internal.ads.zzapt.zzf(com.google.android.gms:play-services-ads-lite@@20.0.0:4)
E/Ads     (24079): 	at com.google.android.gms.internal.ads.zzapv.zzbz(com.google.android.gms:play-services-ads-lite@@20.0.0:6)
E/Ads     (24079): 	at com.google.android.gms.internal.ads.zzhw.onTransact(com.google.android.gms:play-services-ads-base@@20.0.0:3)
E/Ads     (24079): 	at android.os.Binder.transact(Binder.java:949)
E/Ads     (24079): 	at gc.ba(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:2)
E/Ads     (24079): 	at com.google.android.gms.ads.internal.mediation.client.b.e(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:1)
E/Ads     (24079): 	at com.google.android.gms.ads.nonagon.signals.dd.a(Unknown Source:4)
E/Ads     (24079): 	at aaa.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:2)
E/Ads     (24079): 	at zn.run(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:3)
E/Ads     (24079): 	at aac.run(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
E/Ads     (24079): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Ads     (24079): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Ads     (24079): 	at java.lang.Thread.run(Thread.java:919)
E/Ads     (24079): Error calling adapter: com.google.ads.mediation.adcolony.AdColonyMediationAdapter



I/ExoPlayerImpl(24079): Init ExoPlayerLib/2.4.2 [starqlteue, SM-G960U1, samsung, 29]
W/ll.colormatter(24079): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
I/System.out(24079): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(24079): (HTTPLog)-Static: isSBSettingEnabled false
W/ll.colormatter(24079): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/ll.colormatter(24079): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
W/Ads     (24079): Precache exception
W/Ads     (24079): com.google.android.gms.ads.exoplayer3.upstream.i: Unable to connect to https://r9---sn-2x3een76.gvt1.com/videoplayback?expire=1620416671&ei=HyiVYOK2OM3DqQGx67rACw&ip=45.135.186.135&id=a8fcdaad901a86ee&itag=22&source=web_video_ads&requiressl=yes&ocid=o-ALqI_LluDl4eNRoaabNMerPEK848r8v-5g&hcs=sd&mh=tB&mm=28&mn=sn-2x3een76&ms=nvh&mv=m&mvi=9&pl=25&rmhost=r1---sn-2x3een76.gvt1.com&shardbypass=yes&smhost=r1---sn-2x3een7d.gvt1.com&susc=gvp&acao=yes&ctier=L&mime=video%2Fmp4&vprv=1&dur=15.766&lmt=1616848622211861&mt=1620387621&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cocid%2Csusc%2Cacao%2Cctier%2Cmime%2Cvprv%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAO8w3g26nInZcWnDGsptshNBwRJiCk-K_KU5vAgit0shAiAEB-vOr6z-ToSfQ7vmvotOhoB5hqpnZBC_fpqWpJ4peg%3D%3D&lsparams=hcs%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crmhost%2Cshardbypass%2Csmhost&lsig=AG3C_xAwRQIgGJhiM0kAh1FpTLF7GcJJaJ0GOggEvur_hiPKFyiBjp8CIQDzeHR8FN5ubGbfpE0t14bpUcWJZdmh9JUGcPonl692cQ%3D%3D&cpn=2-SpDgdNckCLNBVm&ic=gmasdk
W/Ads     (24079): 	at com.google.android.gms.ads.exoplayer3.upstream.h.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:19)
W/Ads     (24079): 	at com.google.android.gms.ads.internal.video.exoplayer3.p.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:30)
W/Ads     (24079): 	at com.google.android.gms.ads.exoplayer3.upstream.n.run(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:4)
W/Ads     (24079): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Ads     (24079): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Ads     (24079): 	at java.lang.Thread.run(Thread.java:919)
W/Ads     (24079): Caused by: java.net.SocketTimeoutException: SSL handshake timed out
W/Ads     (24079): 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/Ads     (24079): 	at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@211515039@21.15.15 (120408-371058782):6)
W/Ads     (24079): 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@211515039@21.15.15 (120408-371058782):16)
W/Ads     (24079): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1471)
W/Ads     (24079): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1415)
W/Ads     (24079): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1359)
W/Ads     (24079): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
W/Ads     (24079): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
W/Ads     (24079): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
W/Ads     (24079): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
W/Ads     (24079): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
W/Ads     (24079): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:483)
W/Ads     (24079): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:135)
W/Ads     (24079): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
W/Ads     (24079): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
W/Ads     (24079): 	at com.google.android.gms.ads.exoplayer3.upstream.h.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:11)
W/Ads     (24079): 	... 5 more


I/flutter (24079): Error Rewarded Video Ad failed to load: #-1: Timeout achieved
I/Ads     (24079): Ad failed to load : 0
W/Ads     (24079): Failed to preload url gcache://video/media/-6269896142224718098?url=https%3A%2F%2Fr9---sn-2x3een76.gvt1.com%2Fvideoplayback%3Fexpire%3D1620416671%26ei%3DHyiVYOK2OM3DqQGx67rACw%26ip%3D45.135.186.135%26id%3Da8fcdaad901a86ee%26itag%3D22%26source%3Dweb_video_ads%26requiressl%3Dyes%26ocid%3Do-ALqI_LluDl4eNRoaabNMerPEK848r8v-5g%26hcs%3Dsd%26mh%3DtB%26mm%3D28%26mn%3Dsn-2x3een76%26ms%3Dnvh%26mv%3Dm%26mvi%3D9%26pl%3D25%26rmhost%3Dr1---sn-2x3een76.gvt1.com%26shardbypass%3Dyes%26smhost%3Dr1---sn-2x3een7d.gvt1.com%26susc%3Dgvp%26acao%3Dyes%26ctier%3DL%26mime%3Dvideo%252Fmp4%26vprv%3D1%26dur%3D15.766%26lmt%3D1616848622211861%26mt%3D1620387621%26txp%3D5311224%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Citag%252Csource%252Crequiressl%252Cocid%252Csusc%252Cacao%252Cctier%252Cmime%252Cvprv%252Cdur%252Clmt%26sig%3DAOq0QJ8wRQIhAO8w3g26nInZcWnDGsptshNBwRJiCk-K_KU5vAgit0shAiAEB-vOr6z-ToSfQ7vmvotOhoB5hqpnZBC_fpqWpJ4peg%253D%253D%26lsparams%3Dhcs%252Cmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%252Crmhost%252Cshardbypass%252Csmhost%26lsig%3DAG3C_xAwRQIgGJhiM0kAh1FpTLF7GcJJaJ0GOggEvur_hiPKFyiBjp8CIQDzeHR8FN5ubGbfpE0t14bpUcWJZdmh9JUGcPonl692cQ%253D%253D%26cpn%3D2-SpDgdNckCLNBVm%26ic%3Dgmasdk&tag.duration=16000&tag.check_url=https%3A%2F%2Fr9---sn-2x3een76.gvt1.com%2Fvideoplayback%3Fexpire%3D1620416671%26ei%3DHyiVYOK2OM3DqQGx67rACw%26ip%3D45.135.186.135%26id%3Da8fcdaad901a86ee%26itag%3D22%26source%3Dweb_video_ads%26requiressl%3Dyes%26ocid%3Do-ALqI_LluDl4eNRoaabNMerPEK848r8v-5g%26hcs%3Dsd%26mh%3DtB%26mm%3D28%26mn%3Dsn-2x3een76%26ms%3Dnvh%26mv%3Dm%26mvi%3D9%26pl%3D25%26rmhost%3Dr1---sn-2x3een76.gvt1.com%26shardbypass%3Dyes%26smhost%3Dr1---sn-2x3een7d.gvt1.com%26susc%3Dgvp%26acao%3Dyes%26ctier%3DL%26mime%3Dvideo%2Fmp4%26vprv%3D1%26dur%3D15.766%26lmt%3D1616848622211861%26mt%3D1620387621%26txp%3D5311224%26sparams%3Dexpire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cocid%2Csusc%2Cacao%2Cctier%2Cmime%2Cvprv%2Cdur%2Clmt%26sig%3DAOq0QJ8wRQIhAO8w3g26nInZcWnDGsptshNBwRJiCk-K_KU5vAgit0shAiAEB-vOr6z-ToSfQ7vmvotOhoB5hqpnZBC_fpqWpJ4peg%3D%3D%26lsparams%3Dhcs%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crmhost%2Cshardbypass%2Csmhost%26lsig%3DAG3C_xAwRQIgGJhiM0kAh1FpTLF7GcJJaJ0GOggEvur_hiPKFyiBjp8CIQDzeHR8FN5ubGbfpE0t14bpUcWJZdmh9JUGcPonl692cQ%3D%3D%26cpn%3D2-SpDgdNckCLNBVm Exception: ExoPlayer was released during preloading.
```

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.2 20D80 darwin-x64, locale en-US)
    • Flutter version 2.0.5 at /Users/ME/development/flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Volumes/ME/Applications/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Volumes/ME/Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • iPho (mobile) • bcccbe93864b12b2d3422cdbaecf25da9ac75d28 • ios            • iOS 14.4.2
    • Chrome (web)        • chrome                                   • web-javascript • Google
      Chrome 90.0.4430.93

• No issues found!

```
</details>

**Comment by bdlukaa** [comment]
Are you using mediation?

**Comment by zenkog** [comment]
Yes I am. 

> Are you using mediation?

**Comment by bdlukaa** [comment]
It's not tested. See https://github.com/bdlukaa/native_admob_flutter/issues/1

**Comment by zenkog** [comment]
ok. then I'll close this for now
