### ISSUE TITLE
Native ad loading hangs with a NullPointerException

### ISSUE THREAD

**Issue by shimaatech** [bdlukaa/native_admob_flutter#64]
Sometimes when loading native ad, it keeps loading while showing the following error message in the console:

```
W/Ads     (12456): NullPointerException occurs when invoking a method from a delegating listener.
W/Ads     (12456): java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri com.google.android.gms.ads.nativead.NativeAd$Image.getUri()' on a null object reference
W/Ads     (12456): 	at com.bruno.native_admob_flutter.native.NativeAdmobController$loadAd$2.onAdLoaded(Controller.kt:139)
W/Ads     (12456): 	at com.google.android.gms.internal.ads.zzvj.onAdLoaded(com.google.android.gms:play-services-ads-lite@@19.8.0:12)
W/Ads     (12456): 	at com.google.android.gms.internal.ads.zzxb.zza(com.google.android.gms:play-services-ads-lite@@19.8.0:11)
W/Ads     (12456): 	at com.google.android.gms.internal.ads.zzgy.onTransact(com.google.android.gms:play-services-ads-base@@19.8.0:13)
W/Ads     (12456): 	at android.os.Binder.transact(Binder.java:949)
W/Ads     (12456): 	at gc.bb(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:2)
W/Ads     (12456): 	at com.google.android.gms.ads.internal.client.al.f(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
W/Ads     (12456): 	at com.google.android.gms.ads.nonagon.shim.t.a(Unknown Source:0)
W/Ads     (12456): 	at com.google.android.gms.ads.nonagon.slot.common.q.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:2)
W/Ads     (12456): 	at com.google.android.gms.ads.nonagon.shim.x.bj(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
W/Ads     (12456): 	at com.google.android.gms.ads.nonagon.shim.loaders.e.run(Unknown Source:0)
W/Ads     (12456): 	at android.os.Handler.handleCallback(Handler.java:883)
W/Ads     (12456): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/Ads     (12456): 	at qy.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
W/Ads     (12456): 	at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:1)
W/Ads     (12456): 	at qy.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
W/Ads     (12456): 	at android.os.Looper.loop(Looper.java:237)
W/Ads     (12456): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
W/Ads     (12456): 	at java.lang.reflect.Method.invoke(Native Method)
W/Ads     (12456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
W/Ads     (12456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by bdlukaa** [comment]
Reproducible on the latest master.

**Comment by shimaatech** [comment]
Hi @bdlukaa

is there any workaround for this? or maybe I should use an older version?

Thanks

**Comment by bdlukaa** [comment]
Yep, use 1.3.0. It was introduced on 1.3.1

**Comment by shimaatech** [comment]
Actually I'm getting this in 1.3.0 also and even in 1.2.4...
Maybe I'm doing something wrong?
I'm simply using NativeAds inside a ListView

**Comment by shimaatech** [comment]
sorry I was wrong... it's not reproducible in 1.3.0
Thanks!

**Comment by bdlukaa** [comment]
Hello. Can you try the latest master?

```yaml
dependencies:
  native_admob_flutter:
    git:
      url: https://github.com/bdlukaa/native_admob_flutter.git
```

**Comment by shimaatech** [comment]
the issue is not reproducible with the latest master
